# Generated by Django 4.2.7 on 2024-02-13 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_resource_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='course.lesson'),
        ),
    ]
