# Generated by Django 4.2.7 on 2024-02-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_resource_lesson_resource_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
