# Generated by Django 4.2.7 on 2024-02-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_chapter_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_images/'),
        ),
    ]
