# Generated by Django 4.2.7 on 2024-06-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(),
        ),
    ]
