# Generated by Django 4.2.7 on 2024-07-09 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0011_alter_chapter_content_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='courses_subscribed', to=settings.AUTH_USER_MODEL),
        ),
    ]
