# Generated by Django 4.2.7 on 2023-11-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_requester_task_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
