# Generated by Django 4.2.7 on 2023-12-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='requester',
        ),
        migrations.DeleteModel(
            name='Requester',
        ),
    ]
