# Generated by Django 4.2.7 on 2023-12-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='task_images'),
        ),
    ]
