# Generated by Django 4.2.7 on 2023-12-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_attached_file_alter_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='company_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='company_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='company_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='company_size',
            field=models.CharField(choices=[('size_1_9', '1-9'), ('size_10_49', '10-49'), ('size_50_99', '50-99'), ('size_100', '100+')], default='size_1_9', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='company_zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
