# Generated by Django 4.2.7 on 2023-12-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_amount_task_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='changed_at',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('accepted', 'Accepted'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
