# Generated by Django 4.2.7 on 2023-12-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_changed_at_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='company_website',
            field=models.URLField(default='https://example.com'),
        ),
    ]
