# Generated by Django 4.2.7 on 2023-12-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
