# Generated by Django 4.2.7 on 2023-12-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='content',
            new_name='motivation',
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(default='', upload_to='resumes/'),
        ),
    ]
