# Generated by Django 4.2.7 on 2024-01-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_application_assigned_task_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
