# Generated by Django 4.2.7 on 2024-01-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, default='nick-morrison-FHnnjk1Yj7Y-unsplash.jpg', null=True, upload_to='category_icons/'),
        ),
    ]
