# Generated by Django 4.2.7 on 2024-01-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_rename_motivation_application_cover_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.skill'),
        ),
    ]
