# Generated by Django 4.2.7 on 2024-07-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_application_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('accepted', 'Accepted'), ('archived', 'Archived'), ('favorite', 'Favorite'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
